"""empty message

Revision ID: 0926f31c3cf0
Revises: b78d66ddb7c7
Create Date: 2024-04-20 15:18:29.441999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0926f31c3cf0'
down_revision = 'b78d66ddb7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city_region_id', sa.Integer(), nullable=True),
    sa.Column('gym_leader', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['city_region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_leader'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
