"""empty message

Revision ID: bf32144631d9
Revises: b646b226e58e
Create Date: 2024-04-22 22:50:34.043051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf32144631d9'
down_revision = 'b646b226e58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_constraint('region_name_key', type_='unique')
        batch_op.drop_constraint('region_professor_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_unique_constraint('region_professor_key', ['professor'])
        batch_op.create_unique_constraint('region_name_key', ['name'])

    # ### end Alembic commands ###
